### ISSUE TITLE
Feature 1 User can view the Splash/start page

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#1]
---
name: New Feature
about: Use this template for adding a new feature to the app.
title: "Feature: User can "
---
​
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​User can click "start" or "login" of the Splash page.
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​User will see two icons and be able to click either one of them.
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-06 at 9 01 23 PM](https://user-images.githubusercontent.com/55678486/117396184-4cbe1400-aeae-11eb-955a-7031e1f212fc.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] ... 
- [ ] ...Create two buttons
- [ ] ...Create the skeleton layout
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
