### ISSUE TITLE
Feature 2 User can Login/register or start without logging in

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#2]
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

User can create an account or login.
User can start the app immediately without logging in. 
​
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

User can choose to login and use the application or use the application without logging in.
User can sign in if username already exists.
User can create an account and fill in the information "username", "first name", "last name", "email", and "password".
​
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

![Screen Shot 2021-05-08 at 10 53 52 AM](https://user-images.githubusercontent.com/55678486/117548853-fa830d00-afeb-11eb-8bf7-9fbadd6bffbc.png)

​
## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] Create API endpoint for user.
- [ ] Allow user to register a new account in db.
- [ ] Make sure passwords and account match when logging in.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
