### ISSUE TITLE
Feature 3 Allow User to input amount of people voting and add a suggestion

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#3]
​
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​User can add how many people are participating in the vote.
User can add a suggestion to be voted on.
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​User can choose how many people will participate in the vote.
User can input a suggestion.
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-08 at 10 59 50 AM](https://user-images.githubusercontent.com/55678486/117549038-19ce6a00-afed-11eb-9265-17d9d70b9303.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​

- [ ] User can choose the amount of people in the group that will vote.
- [ ] Each voter will be able to type in a suggestion.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
