### ISSUE TITLE
User can Vote and Click

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#4]
​
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

User can  vote on everyone's suggestions.
​
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​ User can make a selection and click on what he wants to vote on.
User can click on the submit button for the selection to be finalized. 
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] ... 
- [ ] Populate the options area with the suggestions that everyone has submitted. 
- [ ] Allow each user to individually make a choice and save the choice they made.
- [ ] At the end, after each individual has voted, tally the votes and see which suggestion has the most votes and declare a winner. 

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
