### ISSUE TITLE
User can view results 

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#5]
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​After tallying all the votes, the final results will show and the winning suggestion declared.

## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​The user will be able to see the victor and the result of everyone's voting.

​
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-08 at 1 34 02 PM](https://user-images.githubusercontent.com/55678486/117552726-15f91280-b002-11eb-9fc9-7b8cf93387c5.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] Show a splash page saying the voting has concluded.
- [ ] User is able to click the next button to verify that voting has ended and is ready to see the results. 
- [ ] Tally the votes up and have the one with the most votes appear.
- [ ] The winner will be shown in the designated area.
- [ ] Create a button that will allow the User to go back to the main default page.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
