### ISSUE TITLE
Feature 6 User menu

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#6]
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​User can create and view their own customized favorite lists.
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​User can create a new favorite list.
User can view previously created lists.
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-08 at 1 38 31 PM](https://user-images.githubusercontent.com/55678486/117552864-d8e15000-b002-11eb-9547-5c206ef2ce70.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​

- [ ] Make the "Create New Favorite List" opens to the "create new favorite list"
- [ ] Make the "My Favorites" show the currently saved favorite lists.
- [ ] Add a button to allow the user to go back to the main page.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
