### ISSUE TITLE
Feature 7 User can create a new favorite list

### ISSUE THREAD

**Issue by michael5522** [michael5522/final#7]
## ⚙️ Feature
​
> ##### What capability will users have when this feature is merged?
​

​User can add a new list to save to their own favorites.
## �� Functionality
​
> ##### A description of how the application will work from the perspective of the user.
​

​​User can choose the quality of suggestions to add. 
User can type in the suggestions to be saved.
## ��️ Wireframes
​
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
​

​
![Screen Shot 2021-05-08 at 1 46 22 PM](https://user-images.githubusercontent.com/55678486/117553064-1beff300-b004-11eb-9f31-dfc4fccca105.png)

## ✅ Task List
​
> ##### Commit checklist for tasks needed to complete the feature.
​
- [ ] Allow user to save create a name to save the "user list" as.
- [ ] Allow user to toggle how many suggestions to add to the list.
- [ ] When selection is made, the "click to continue" button will create a new window with the settings user has chosen.
- [ ] Allow User to fill in the suggestions and save.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
